SKILLS = [
    "Python",
    "WSL",
    "SQL",
    "REST",
    "API",
    "Docker",
    "Linux",
    "Django",
    "Postrgresql",
    "Artificial Learning",
    "Js",
    "Machine Learning",
    "React",
    "OOP",
    "Flask",
    "NoSQL",
    "networking",
    "HTML",
    "CSS",
    "DRF",
    "FastAPI",
    "FullStack",
    "asyncio",
    "GraphQL",
    "algorithms",
    "MongoDB",
    "microservice",
    "Tableau"
]

ROLES = {
        "Intern": "Intern",
        "Стажер": "Intern",
        "Стажування": "Intern",
        "Junior": "Junior",
        "Младший": "Junior",
        "Молодший": "Junior",
        "Middle": "Middle",
        "Средний": "Middle",
        "Середній": "Middle",
        "Senior": "Senior",
        "Старший": "Senior",
        "Аналітик": "Analyst",
        "Аналитик": "Analyst",
        "Analyst": "Analyst",
        "Data Scientist": "Data Scientist",
        "Developer": "Developer",
        "Разработчик": "Developer",
        "Розробник": "Developer",
        "Engineer": "Engineer",
        "Инженер": "Engineer",
        "Інженер": "Engineer",
        "Manager": "Manager",
        "Менеджер": "Manager",
        "Project Manager": "Project Manager",
        "Product Manager": "Product Manager",
        "Team Lead": "Team Lead",
        "Technical Lead": "Technical Lead",
        "Tech Lead": "Technical Lead"
    }
